modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/Yucareux/Tellus/issues"

[[mods]]
modId="tellus"
version="${version}"
displayName="Tellus"
displayURL="https://github.com/Yucareux/Tellus"
authors="Me!"
displayTest="IGNORE_ALL_VERSION"
description='''
Tellus is a Forge mod that recreates real-world terrain in Minecraft by generating Earth-scale landscapes from geographic data.
'''

[[dependencies.tellus]]
modId="forge"
mandatory=true
versionRange="[${forgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.tellus]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"

[[dependencies.tellus]]
modId="distanthorizons"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
