pluginManagement {
	repositories {
		maven {
			name = 'NeoForge'
			url = 'https://maven.neoforged.net/releases/'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'UniminedKappa'
			url = 'https://maven.outlands.top/releases/'
		}
		maven {
			name = 'Unimined'
			url = 'https://maven.wagyourtail.xyz/releases/'
		}
		maven {
			name = 'Forge'
			url = 'https://maven.minecraftforge.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'Tellus'

include('mc1211')
include('mc1211-neoforge')
include('mc262')
include('mc262-neoforge')
include('mc1201')
include('mc1201-forge')

dependencyResolutionManagement {
	repositories {
		mavenCentral()
	}
}
