modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-only"
issueTrackerURL="https://github.com/Yucareux/Tellus/issues"

[[mods]]
modId="tellus"
version="${version}"
displayName="Tellus"
displayURL="https://github.com/Yucareux/Tellus"
authors="Me!"
description='''
Tellus is a NeoForge mod that recreates real-world terrain in Minecraft by generating Earth-scale landscapes from geographic data.
'''

[[mixins]]
config="tellus.mixins.json"

[[mixins]]
config="tellus.client.mixins.json"

[[dependencies.tellus]]
modId="neoforge"
type="required"
versionRange="[${neoForgeVersion},)"
ordering="NONE"
side="BOTH"

[[dependencies.tellus]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"

[[dependencies.tellus]]
modId="distanthorizons"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
